[build]
command = "npm run build"
functions = "./functions"
publish = "dist/ecomm-project"
[dev]
# command = 'npm run start'
command = 'npm run api'
publish = 'src'

[[redirects]]
# from = "/*"
# to = "/index.html"
status = 200

